# Uncomment the next line to define a global platform for your project
# platform :osx, '10.15'

target 'MoonLightDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'MoonLight_macOS', :podspec => '../../../MoonLight_macOS.podspec'
  # Pods for MoonLightDemo

end
