# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MoonLightDemo_iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'MoonLight_iOS', :podspec => '../../../MoonLight_iOS.podspec'
  # Pods for MoonLightDemo_iOS

end
